### ISSUE TITLE
Is vlcj 5 definitely released? Why can't I find it in maven repository?

### ISSUE THREAD

**Issue by Apyz** [caprica/vlcj#1201] opened 2023-08-25 23:23 UTC
The highest vlcj version available is 4.8.2, but 5.0.0 is invalid

**Comment by caprica** [comment] 2023-08-26 15:51
vlcj 5.x is NOT released yet. This is because VLC 4.0.0 is not released yet either.

You CAN get vlcj 5.x from the Maven Snapshot repository, so enable Maven snapshots in your pom.xml.

Dupe of #1103 .

**Closed** 2023-09-06 05:07 UTC
Labels: Support
