### ISSUE TITLE
how can I play the video based on the format of 4K( or x264/x265 )

### ISSUE THREAD

**Issue by ShellMount** [caprica/vlcj#560] opened 2017-06-10 13:23 UTC
I have managed to play a 4K video from the DEMO of vlcj-player , however, you will find difficult to play it.
the video was played frame by frame, that is not smooth.
What I need do ?

**Comment by caprica** [comment] 2017-06-10 14:21
vlcj does not actually play your video. It embeds a heavyweight component and it passes the ID of that component to LibVLC and then it is VLC that plays your video.

Does the standalone VLC player play your 4k video OK? If so, are you sure you are using the same version of VLC with standalone and with vlcj?

I can not see how this can be a vlcj problem, but I do not have any 4k video to test. Do you know of any public, unencumbered, 4k video samples?

**Comment by ShellMount** [comment] 2017-06-10 15:16
as test the 4k file playing, I have uploaded a sample file,
it is more  than 10M( size of 250M ), you can down the file by the tmp url:
http://test4k.imqk.com/HD.-4K.mp4.tar

more info: my local vlc version:  vlc_2.2.4.0

@caprica 
thanks.

**Comment by caprica** [comment] 2017-06-10 18:18
But you didn't answer the other question: does the standalone VLC player play your video without any problems?

**Comment by caprica** [comment] 2017-06-10 18:27
I tried your sample video in my own vlcj-player application. My CPU and GPU are about 1.5 years old I think, i really don't recall, and were pretty good specs at the time. The video plays smoothly, but the Java application does use over 100% CPU.

I still don't think there is anything that can be changed in vlcj to help you, I think instead it is simply that 4K video is very resource intensive.

**Comment by caprica** [comment] 2017-06-10 18:28
Are you sure vlc 2.2.x even supports 4K video properly?

**Comment by ShellMount** [comment] 2017-06-11 02:03
No problem playing on the player of standalone  VLC.
@caprica

**Comment by ShellMount** [comment] 2017-06-11 03:07
I also think nothing will be changed about vlcj,
maybe some setting are necessary in the vlcj-player to keep playing smoothly and supply 4k(HD) videos.
however, I don't know where (which options) should be adjusted.

**Comment by ShellMount** [comment] 2017-06-11 03:14
more info:
http://test4k.imqk.com/HD.-4K.mp4.tar
the above video can be played smoothly on officail standalone VLC, version 2.2.4.0.
and is ok on the other players (such as KMP, and so on)

but, it is not smoothly on the demo of vlcj-player .
and, the non-4k(HD) videos have a good performance on the vlcj-player .

so, I really want to know what should I do to impove the performance  about playing 4k(hd) videos.

**Comment by teabagD** [comment] 2018-02-01 22:03
Hi I can confirm this issue.
60 fps 4k videos play at 60 fps without any problem in the standalone VLC player. My computer is quite powerful and in fact I can play 2 of those videos in the standalone VLC Players at the same time at a smooth 60fp each.

However when playing the videos using vlcj, rendering onto a Swing canvas, or even using the direct media player, without rendering the frames anywhere, I get choppy video. Frame rates can drop down to as low as 45 fps at times.

To me this seems like it might be a VLC configuration issue. 

A thing I noticed while testing this, was that once I opened 3 instances of the standalone VLC player with the high def video, the players that weren't in the foreground would be choppy(i.e. less then 60 fps) while the foreground player would still play at a smooth 60 fps.

A wild guess, which I know is likely to be wrong is that VLC limits the amount of resources it uses when it is not in the foreground, and perhaps running it through java jni somehow keeps it from ever getting into foreground.

**Comment by caprica** [comment] 2018-02-01 22:34
So can you even say the bottleneck is VLC or the JVM? That at least would be a start. But I'm really not sure what could be done in vlcj - essentially vlcj gives LibVLC a native window handle (the Canvas) and tells VLC to render it's video there. That's it.

**Comment by teabagD** [comment] 2018-02-02 11:04
Just did a test running VLC from a C++ app and got same performance as with VLCJ. So it's definitely vlc itself.

**Comment by caprica** [comment] 2018-02-02 11:17
That's interesting, thanks.

**Comment by caprica** [comment] 2018-11-07 18:50
Leaving this issue open as a reminder to document this somewhere.

**Comment by caprica** [comment] 2019-01-14 13:46
I'm not sure but hardware decoding seems to be enabled by default with VLC 3.x.

**Comment by caprica** [comment] 2019-02-01 12:12
I'm now going to close this as it's confirmed that hardware decoding is now enabled by default from VLC 3.0.0 onwards.

https://www.videolan.org/news.html#news-2018-02-09

**Closed by caprica** 2019-02-01 12:12 UTC
Labels: Support
