### ISSUE TITLE
Getting an exception every time release() is called

### ISSUE THREAD

**Issue by drstevendejong** [caprica/vlcj#1009] opened 2020-09-29 17:26 UTC
I've tried everything, but calling

`embeddedMediaPlayer.media().prepare(myVideo);`

twice ALWAYS gives me an exception (in the native code) because of `release()` being called.

**Comment by caprica** [comment] 2020-09-29 17:34
Posting the exception would be helpful.

**Comment by caprica** [comment] 2020-09-29 17:36
Or are you saying there's no Java exception, only a native fatal crash?

**Comment by caprica** [comment] 2020-09-29 18:41
Unable to reproduce this, post a self-contained example, whatever stack-traces or hotspot crash logs you have and which versions you are using if you want any more help.

**Comment by caprica** [comment] 2020-09-30 16:37
If you can post the requested information please do so, otherwise I'll close this in the next day or so.

**Closed** 2020-10-01 18:08 UTC
Labels: Support
