### ISSUE TITLE
RAM usage is getting high when mediaplayer repeat set to true

### ISSUE THREAD

**Issue by androuino** [caprica/vlcj#902] opened 2019-09-27 04:36 UTC
Hello guys,

currently this is how I implemented my **JavaFX** application using this library, however setting the **MediaPlayerComponent** `repeat` to true increases the RAM usage little by little.

What am doing is that, I have 3 videos which is 10 seconds in length, whenever the 1st video has finished playing, Am going to click a button and start playing the next video then the very last one. But whenever the video is finished, the memory used will still be the same and doesn't go back (I don't know, maybe to the default RAM usage amount that the app should be using?).

I've also noticed that it is also happening if `repeat` is not set to true. If I start my App without doing anything, it consumes 7.86G of RAM then it will start increasing little by little let say upto 11G of RAM usage if I do what I mentioned above.

OS = Xubuntu 18.04
CPU = i7 8-threads
RAM = 16GB
JavaFX = 11.0.2
VLCJ = 3.12.1
JDK = openjdk11

```
if (mediaPlayerComponent != null) {
      mediaPlayerComponent?.mediaPlayer?.stop()
      mediaPlayerComponent?.mediaPlayer?.release()
      mediaPlayerComponent = null
      writableImage = null
      imageView = null
      videoSourceRatioProperty = null
      canvas = null
      writablePixelFormat = null
}


writableImage = WritableImage(stackPaneMain.width.toInt(), stackPaneMain.height.toInt())
imageView = ImageView(writableImage)
imageView?.fitWidthProperty()?.bind(stackPaneMain.widthProperty())
imageView?.fitHeightProperty()?.bind(stackPaneMain.heightProperty())
videoSourceRatioProperty = SimpleFloatProperty(0.4f)
canvas = Canvas()
pixelWriter = canvas?.graphicsContext2D?.pixelWriter
writablePixelFormat = PixelFormat.getByteBgraPreInstance()
mediaPlayerComponent = CanvasPlayerComponent()
mediaPlayerComponent?.mediaPlayer?.prepareMedia(file.absolutePath)
mediaPlayerComponent?.mediaPlayer?.play()
if (isContinuous) {
      mediaPlayerComponent?.mediaPlayer?.repeat = true
}
groupMedia.children.add(imageView)
```

So I hope you guys could say something about this, If you experienced the same thing please would you be kind and share your workaround or solution to my problem. Thank you very much.

**Comment by caprica** [comment] 2019-09-27 06:08
So the fact you set repeat or not is irrelevant, right?

I suspect you are seeing leaks in native memory quite honestly. I profiled vlcj and it's Java memory usage a while back and never saw any leaks. In fact typical vlcj apps use very little Java memory, iirc it was on the order of 20mb or so.

So, for me to look at this I would need proof from a Java profiler that there is a JVM heap memory leak and that the leaks were in vlcj classes and not your own application classes.

Otherwise you need to somehow do native memory profiling and that will likely show up a leak outside of vlcj.

Even then the problem is nebulous so it's hard to say any more.

**Comment by caprica** [comment] 2019-09-27 06:10
For your application to consume almost 8gb of memory on startup is very suspect, so what JVM settings are you using?

**Comment by androuino** [comment] 2019-09-27 06:13
Thank you for you quick response. I don't have a JVM settings yet at the moment but since I also noticed that a startup of almost 8GB of RAM is suspicious, so I will probably look into it more deeply.

**Comment by androuino** [comment] 2019-09-27 06:21
Oh, sorry my mistakes, since I was looking the cpu and memory usage using HTOP, I've mistakenly thought that starting the JFX App took almost 8GB but that's is wrong, it's only 0.63GB at startup.

**Comment by sghpjuikit** [comment] 2019-09-27 07:07
I know this is off topic, but I really want to point out that the way you are using the `?` operator is sub-optimal at best. Instead:
```
imageView = ImageView(writableImage)
imageView?.fitWidthProperty()?.bind(stackPaneMain.widthProperty())
```
it is better to do
```
imageView = ImageView(writableImage).apply {
    imageView.fitWidthProperty().bind(stackPaneMain.widthProperty())
}
```
Local variables and scoping functions are your friends.

**Comment by androuino** [comment] 2019-09-27 07:25
oh I see, thanks for pointing that out @sghpjuikit.

**Comment by caprica** [comment] 2019-09-27 12:04
Even 0.6gb seems high. Vlcj does not need much memory at all.

**Comment by androuino** [comment] 2019-09-28 01:38
That's a start without running the vlcj library. Maybe because of the JavaFX?

**Comment by caprica** [comment] 2019-09-29 14:09
Oh, maybe. Also it will depend on the default heap-size set for your JVM of course.

Back to the main point, I will be very surprised if vlcj is causing your memory leaks, the only way to know for sure is to at least run a Java heap profiler (JVisualVM or one of the commercial ones). 

I don't know too much about profiling native applications however, only Java ones.

**Comment by androuino** [comment] 2019-09-30 02:04
I've looked closely with my code and release carefully released all instances of UI related views and therefore I conclude that I have missed to release some of my views then I tested the vlcj again and the memory got stable though in spite of not having a heap size memory setting for JVM.

So the test I did is, playing up to maximum of 10 different videos with 10secs each in length, switching videos in a rapid way like less 3secs then switch to a different video and am happy with the result.

I would love to test the RAM usage with profiler also or some memory leaks identifier that is similar to Android's **leakcanary**.

**Comment by caprica** [comment] 2019-09-30 18:48
I'll close this since you seem to have resolved the problem.

If evidence is provided showing a memory leak in vlcj, unlikely IMO, this can be reopened.

**Closed by caprica** 2019-09-30 18:48 UTC
Labels: Support
