### ISSUE TITLE
Fatal Error when using scroll wheel/mouse buttons

### ISSUE THREAD

**Issue by a-lex-ant** [caprica/vlcj#923] opened 2020-03-02 09:42 UTC
Hello,

I'm encountering a fatal JRE error every time I try to use my mouse's scroll wheel and/or click on anything that is not a button.

I've already opened an issue with the programmer of the Look and Feel I am using, but he suggested I notify you too, as it seems to be a Vlcj problem.
You can find the error log and the workaround he's found in [my original post](https://github.com/JFormDesigner/FlatLaf/issues/74).

Thank you

**Comment by caprica** [comment] 2020-03-02 10:48
Linking #477

**Comment by caprica** [comment] 2020-03-02 10:49
Please post your application initialisation code showing exactly how and when you are using this look and feel.

**Comment by a-lex-ant** [comment] 2020-03-04 09:26
https://gist.github.com/a-lex-ant/e3c29f3ecb9d9a389aede9d9586720d5

Thanks

**Comment by caprica** [comment] 2020-03-04 20:22
I have seen previously that some L&F have problems if you either initialise them on the Swing EDT, or equally if you do not. I've seen different L&F have problems either way, or not.

At the present time, I don't think I can add too much that hasn't already been said in #477.

I would like to get to the bottom of it, but for now this is not something I can actively look at.

**Comment by a-lex-ant** [comment] 2020-03-06 16:38
Fair enough, I just wanted to give you an heads up that the problem is still presenting itself.
I've already found a fix for my case as you can see in my original post, I hope that posting here will help give it more visibility if another comes here for the same reason as me...

Thanks for your attention!
A.

**Comment by caprica** [comment] 2020-03-06 18:37
I think it's fine to keep the issue open, for now at least.

Unfortunately there just isn't an easy answer.

**Comment by caprica** [comment] 2020-03-26 09:18
I did some looking into this.

There's nothing new to report really, but:

I was able to easily reproduce this if the LookAndFeel was initialised before creating the media player factory
I was trivially able to prevent the crash by making sure the media player factory was initialised before the LookAndFeel
There is clearly some initialisation race in native code somewhere, but digging into and debugging native code is not on my agenda especially when it is possible to workaround the problem with some reordering of initialisation code.

Having said that, if I could find a way in vlcj to prevent this happening, that would be useful.

**Comment by caprica** [comment] 2020-04-11 09:05
I'm going to close this now since the workaround is reasonable.

If in the future a solution presents itself I'll look into it again.

**Closed by caprica** 2020-04-11 09:05 UTC
Labels: Support

**Comment by a-lex-ant** [comment] 2020-04-13 08:11
> I'm going to close this now since the workaround is reasonable.
> 
> If in the future a solution presents itself I'll look into it again.

Thanks for your help, much appreciated

**Comment by caprica** [comment] 2020-04-13 08:15
@a-lex-ant I am still hopeful of a proper solution for this, but it's on the long-term list of things to do.
