### ISSUE TITLE
GNUTLS TLS Client error?

### ISSUE THREAD

**Issue by Lordmau5** [caprica/vlcj#323] opened 2015-02-13 21:25 UTC
Whenever it tries to play a video / song / whatever, it runs into this:
http://puu.sh/fSr4v/5d563a24ec.txt

//EDIT: Only Youtube so far, Soundcloud works fine... What could this be? :/

**Comment by caprica** [comment] 2015-02-14 08:43
Probably dupe of #275.

**Closed by caprica** 2015-02-14 08:43 UTC
Labels: Duplicate, Support

**Comment by Lordmau5** [comment] 2015-02-18 14:21
Tried everything that I could and couldn't get it to work, unfortunately.

Updated to VLC 2.1.5 custom build, updated to VLC 3.0.0-git.
Even built the newest GNUTLS myself and installed it - Nothing worked.
I'm still running into the problem.

OS: Ubuntu 14.04.1 LTS

**Comment by caprica** [comment] 2015-02-18 14:24
It is impossible to "fix" this in vlcj.

Are you sure at run-time you are definitely picking up the right (updated) version of LibVLC? The vlcj logs would tell you.

Post a YouTube URL that doesn't work for you and I'll try it.

**Comment by Lordmau5** [comment] 2015-02-18 14:37
Doesn't work with any YouTube Video.
Other things like Soundcloud seem to work fine...

http://puu.sh/g2hoo/8010460a5a.txt
(Inbetween it's outputting those GNUTLS errors, but it didn't want to insert those into the log.txt via. >> log.txt)

**Comment by caprica** [comment] 2015-02-18 14:41
I tried the URL in your log with vlcj and vlc-git.

I use the vlcj YouTubePlayer test example.

Works just fine.

![youtube](https://cloud.githubusercontent.com/assets/1385879/6249018/2e39d2e2-b77c-11e4-99f0-c9134afb7678.png)

**Comment by Lordmau5** [comment] 2015-02-18 14:45
Hmm.. Well, even on Linux it seems that it can find LibVLC, so that's not the problem.

Still, I have no idea on how to fix this...

**Comment by caprica** [comment] 2015-02-18 14:46
Please try the vlcj YouTube player.

**Comment by caprica** [comment] 2015-02-18 14:47
Did you build VLC yourself? There may be a problem with the build of VLC you are using - it may have a wrong TLS library dependency or something. I don't really know about that stuff I'm afraid, but as far as I can see, VLC/vlcj (at least up to date versions) works just fine with YouTube.

**Comment by Lordmau5** [comment] 2015-02-18 14:58
Tried to use your VLCJ Youtube Player, and same result.
http://puu.sh/g2ixT/a7f0773649.txt

And no, I did not build VLC myself.
I added the ppa:videolan/master-daily repository and grabbed the newest 3.0.0-git build from there.

**Comment by caprica** [comment] 2015-02-18 15:03
Well, I don't know.

I'm using Kubuntu 14.10, latest vlc-git built of like 15 minutes ago, I use the same YouTube URL as you, and it works.

Even if it didn't work for me either, it still wouldn't be a vlcj problem (!).

**Comment by caprica** [comment] 2015-02-18 15:04
Wait a minute, your last log shows a *different* error related to the union bug you reported previously (that I fixed with the latest vlcj-git).

**Comment by Lordmau5** [comment] 2015-02-18 15:09
Ye, but that one has nothing to do with the fact, that it can't fill the GnuTLS buffer, does it? :P

**Comment by caprica** [comment] 2015-02-18 15:10
Did you try a VLC nightly build on Windows?

I don't really know what else to suggest.

**Comment by Lordmau5** [comment] 2015-02-18 15:11
I am not facing this problem on Windows. It's only on 14.04 Ubuntu and so far I can't convince my friend to upgrade our server.
Will have another talk with him later today.

I already tried 14.10 in a Virtual Machine and it worked fine in there, so it *has* to be 14.04.

**Comment by caprica** [comment] 2015-02-18 15:20
Ah OK, maybe the TLS client libraries are too old or something like that on 14.04.

**Comment by Lordmau5** [comment] 2015-02-18 16:06
Just checked something for fun.

If I start VLC either over the terminal or the applications menu (VNC) and attempt to play a Youtube video, it works fine (considering the lua-scripts are up2date).

But through either your YoutubePlayer or my own application, it runs into that GnuTLS error...

**Comment by caprica** [comment] 2015-02-18 16:11
Are you sure it's the same VLC version when you do that?

Whatever the case, even though what you've found is an interesting titbit, there is still nothing that can be done in vlcj to fix this.

The API in question is basically (in pseudo code) "play(url)". vlcj doesn't really do anything here.

**Comment by Lordmau5** [comment] 2015-02-18 16:11
Does vlcj have a method to get / return / output the VLC-version that is being used?
I could check by using that, then.

**Comment by caprica** [comment] 2015-02-18 16:13
Yes, it's in your logs already.
```
String ver = LibVlcVersion.getVersion();
```
