### ISSUE TITLE
Invalid memory access when play a video has  mkv format (this file has ASS format subtitles),then play another video.

### ISSUE THREAD

**Issue by tangshimin** [caprica/vlcj#1144] opened 2022-05-13 09:45 UTC
### play a mkv format video has ASS format subtitle, and then play another video,will happen.

```Java
Exception in thread "AWT-EventQueue-0" java.lang.Error: Invalid memory access
	at uk.co.caprica.vlcj.binding.LibVlc.libvlc_media_list_player_stop(Native Method)
	at uk.co.caprica.vlcj.player.list.ControlsApi.stop(ControlsApi.java:72)
	at uk.co.caprica.vlcj.player.base.SubitemApi.changeMedia(SubitemApi.java:106)
	at uk.co.caprica.vlcj.player.base.MediaApi.applyMedia(MediaApi.java:350)
	at uk.co.caprica.vlcj.player.base.MediaApi.changeMedia(MediaApi.java:330)
	at uk.co.caprica.vlcj.player.base.MediaApi.prepare(MediaApi.java:82)
	at uk.co.caprica.vlcj.player.base.MediaApi.play(MediaApi.java:93)
	at uk.co.caprica.vlcjplayer.view.main.RecentMediaMenu$PlayRecentAction.actionPerformed(RecentMediaMenu.java:68)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:374)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:1028)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:1072)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6626)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3389)
	at java.desktop/java.awt.Component.processEvent(Component.java:6391)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:746)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:744)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:743)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

```
<br/>

### this demo use [vlcj-player](https://github.com/caprica/vlcj-player), original video download from [TED](https://download.ted.com/products/88569.mp4?apikey=acme-roadrunner) ,then convert to mkv format.

https://user-images.githubusercontent.com/16540656/168256080-01b6dabc-0ce7-4b70-940a-2f2985fb9013.mp4

**Comment by caprica** [comment] 2022-05-13 10:16
What happens if you use the VLC application itself to play your videos?

**Comment by caprica** [comment] 2022-05-13 10:18
Your version of vlcj is quite old, try with 4.7.2 and see if there's any difference.

**Comment by tangshimin** [comment] 2022-05-13 10:19
> What happens if you use the VLC application itself to play your videos?

can play，no error

**Comment by tangshimin** [comment] 2022-05-13 10:32
4.7.2 ,still happen

**Comment by caprica** [comment] 2022-05-13 11:37
What version of VLC is it?

**Comment by tangshimin** [comment] 2022-05-13 11:38
vlc-3.0.16-win64

**Comment by caprica** [comment] 2022-05-13 11:47
What happens if you do NOT convert it to mkv?

**Comment by tangshimin** [comment] 2022-05-13 11:48
can play

**Comment by tangshimin** [comment] 2022-05-13 11:51
can play, change media no error

**Comment by caprica** [comment] 2022-05-13 11:52
So, either:

 - something wrong with VLC's mkb implementation (unlikely IMO, but not impossible)
 - something wrong with the conversion you did to mkv

I just tested vlcj-player right now with a whole bunch of videos and it all worked for me, I played mp4 files, mkv files, no problems.

**Comment by tangshimin** [comment] 2022-05-13 12:32
I just downloaded a file from: https://www.ted.com/talks/bill_gates_we_can_make_covid_19_the_last_pandemic
convert to mkv use this command
```shell
ffmpeg -i C:\Users\tangs\Videos\TED\2022-bill-gates-002-5000k.mp4  output.mkv
```
still have error

**Comment by caprica** [comment] 2022-05-13 13:42
I can reproduce this issue in fact, when using that ffmpeg conversion.

The crash actually occurs when the media player is stopped via the stop button, or when the media reaches the end and stops - it is not specifically to do with playing another video.

Having said that, this is almost certainly nothing that can be fixed in vlcj, especially as I have tested other mkv files that do not cause the crash.

It does now look like a problem with the mkv conversion by ffmpeg, or that it can not be played via LibVLC without crashing. It is surprising that VLC itself does not crash, but LibVLC and VLC are not quite the same thing.

**Comment by caprica** [comment] 2022-05-13 15:08
I converted another mp4 to mkv, and that did NOT crash.

All of this together strongly suggests there is no problem with vlcj here, I'm afraid the problem is elsewhere.

**Comment by caprica** [comment] 2022-05-15 19:40
Closing, as I do not believe this is a problem with vlcj, nor something that could be fixed in vlcj.

**Closed by caprica** 2022-05-15 19:40 UTC
Labels: Support
