### ISSUE TITLE
java.lang.Error: Invalid memory access when calling mediaPlayer.playMedia

### ISSUE THREAD

**Issue by bogdanbasilescu** [caprica/vlcj#919] opened 2020-02-18 05:45 UTC
Hello,

I am receiving an Error sometimes when calling mediaPlayer.playMedia after getting an error() event in the MediaPlayerEventAdapter. How can I guard the code against this error?

P.S the mediaPlayer call is not in the error() callback. It's triggered upon pressing another overlay button.

Thank you in advance! :)

This is the log dump:

2020-02-17 17:09:39:464 WARNING: java.lang.Error: Invalid memory access	
	at com.sun.jna.Native.invokePointer(Native Method)
	at com.sun.jna.Function.invokePointer(Function.java:477)
	at com.sun.jna.Function.invoke(Function.java:411)
	at com.sun.jna.Function.invoke(Function.java:323)
	at com.sun.jna.Library$Handler.invoke(Library.java:236)
	at com.sun.proxy.$Proxy60.libvlc_media_get_mrl(Unknown Source)
	at uk.co.caprica.vlcj.player.DefaultMediaPlayer.mrl(DefaultMediaPlayer.java:1827)
	at uk.co.caprica.vlcj.player.events.MediaPlayerEventFactory.createEvent(MediaPlayerEventFactory.java:89)
	at uk.co.caprica.vlcj.player.DefaultMediaPlayer$EventCallback.callback(DefaultMediaPlayer.java:2216)
	at sun.reflect.GeneratedMethodAccessor158.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.jna.CallbackReference$DefaultCallbackProxy.invokeCallback(CallbackReference.java:485)
	at com.sun.jna.CallbackReference$DefaultCallbackProxy.callback(CallbackReference.java:515)
	at com.sun.jna.Native.invokeVoid(Native Method)
	at com.sun.jna.Function.invoke(Function.java:374)
	at com.sun.jna.Function.invoke(Function.java:323)
	at com.sun.jna.Library$Handler.invoke(Library.java:236)
	at com.sun.proxy.$Proxy60.libvlc_media_player_set_media(Unknown Source)
	at uk.co.caprica.vlcj.player.DefaultMediaPlayer.setMedia(DefaultMediaPlayer.java:2105)
	at uk.co.caprica.vlcj.player.DefaultMediaPlayer.prepareMedia(DefaultMediaPlayer.java:282)
	at uk.co.caprica.vlcj.player.DefaultMediaPlayer.playMedia(DefaultMediaPlayer.java:263)
	at **uk.co.caprica.vlcj.player.DefaultMediaPlayer.playMedia(DefaultMediaPlayer.java:256)**
	at -----------$playVideoSource$9(------------.java:526)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233)
	at java.awt.Dialog.show(Dialog.java:1084)
	at java.awt.Component.show(Component.java:1671)
	at java.awt.Component.setVisible(Component.java:1623)
	at java.awt.Window.setVisible(Window.java:1014)
	at java.awt.Dialog.setVisible(Dialog.java:1005)
	at -----------.setVisible(MainWindowForWindows.java:147)
	at java.awt.GraphicsDevice.setFullScreenWindow(GraphicsDevice.java:338)
	at sun.awt.Win32GraphicsDevice.setFullScreenWindow(Win32GraphicsDevice.java:367)
	at --------------------.setVisible(MainWindowForWindows.java:135)
	at --------------------.lambda$initApplication$5(ApplicationActivator.java:268)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by caprica** [comment] 2020-02-18 08:00
Most likely something is null.

Without an isolated reproducible test case it's impossible to say what.

**Comment by caprica** [comment] 2020-02-27 21:52
Closing due to lack of follow-up.

**Closed by caprica** 2020-02-27 21:52 UTC
Labels: Support
