### ISSUE TITLE
CallbackMedia does not work.

### ISSUE THREAD

**Issue by smokingrain** [caprica/vlcj#855] opened 2019-04-15 02:54 UTC
Codes like this:
 * mediaPlayerComponent.mediaPlayer().media().play(new RandomAccessFileMedia(new File("xx.mp4")));
does not work,
but :
 * mediaPlayerComponent.mediaPlayer().media().play("xx.mp4");
it works;
so can "RandomAccessFileMedia" really in use?

And I also tried your test case "MinimalMediaCallbackTest",it does not work.

**Comment by caprica** [comment] 2019-04-15 15:53
Well... it does work but... the problem is that your callback media has been garbage collected.
```
mediaPlayerComponent.mediaPlayer().media().play(new RandomAccessFileMedia(new File("xx.mp4")));
```
You declare a heap variable that almost immediately goes out of scope, nothing else references it, so it is eligible for garbage collection and gets collected. When that object goes away, there is no longer any object available for the native code to call back into to read the media.

The solution is to keep a hard reference to your callback media.

As you've spotted the example suffers the same problem.

**Comment by caprica** [comment] 2019-04-15 15:54
I would also add that using this callback media is almost always the wrong solution to whatever you're doing.

While there may be some small number of legitimate use-cases for this stuff, it's usually a bad idea.

**Comment by caprica** [comment] 2019-04-15 15:55
833d0ea269edf6627818cf979fcf1b2343593d08

**Closed by caprica** 2019-04-15 15:55 UTC
Labels: Support

**Comment by caprica** [comment] 2019-04-15 19:10
Created #856 to consider whether anything better can be done.

**Comment by SageLam** [comment] 2019-08-22 08:32
how to keep a hard reference?can you show the code please?

**Comment by SageLam** [comment] 2019-08-22 08:33
> Well... it does work but... the problem is that your callback media has been garbage collected.
> 
> ```
> mediaPlayerComponent.mediaPlayer().media().play(new RandomAccessFileMedia(new File("xx.mp4")));
> ```
> 
> You declare a heap object that almost immediately goes out of scope, nothing else references it, so it is eligible for garbage collection and gets collected. When that object goes away, there is no longer any object available for the native code to call back into to read the media.
> 
> The solution is to keep a hard reference to your callback media.
> 
> As you've spotted the example suffers the same problem.

how to keep a hard reference?can you show the code please?

**Comment by smokingrain** [comment] 2019-08-22 08:59
@SageLam  My callback media never been garbage collected.But，it still not work,and the methods like  onGetSize,onOpen,onRead never called.I don't know why,maybe Windows does not support this function.

**Comment by SageLam** [comment] 2019-08-22 09:05
> @SageLam My callback media never been garbage collected.But，it still not work,and the methods like onGetSize,onOpen,onRead never called.I don't know why,maybe Windows does not support this function.

我用mac测试，可以触发getSize,onOpen之类的方法，但是每次都报这两个错[00007ff239e10a00] imem demux error: Invalid get/release function pointers
[00007ff239ca34a0] imem stream error: Invalid get/release function pointers。要奔溃了。再找不到办法就只能去研究ffmpeg了。

**Comment by smokingrain** [comment] 2019-08-22 09:09
@SageLam give up callbackmedia ,use mrl instead.

**Comment by caprica** [comment] 2019-08-22 10:21
Callback media does work. Did you try the relevant test classes in the vlcj project test sources?

**Comment by smokingrain** [comment] 2019-08-22 11:14
@caprica You are always online bro.I tried MinimalMediaCallbackTest.java,no audio out, no video out.

**Comment by caprica** [comment] 2019-08-22 14:31
Just tried MinimalMediaCallbackTest, works for me.

**Comment by SageLam** [comment] 2019-08-22 14:38
I also tried then just black ground and nothing output .

**Comment by caprica** [comment] 2019-08-22 14:46
Well, maybe you should do a bit of work to help find out why. Enable VLC logs, inspect them, make deductions, and if you can't work it out then post your logs. Are you sure you're using the right filename etc... etc...

When I say it works for me, I went to the trouble of actually trying it. What else do you expect me to do? Shall I come round to your house and debug it for you?

**Comment by smokingrain** [comment] 2019-08-23 01:52
[main                ] (audio output        )   DEBUG: removing module "mmdevice"
[main                ] (input               )   DEBUG: Creating an input for 'imem://'
[main                ] (input               )   DEBUG: using timeshift granularity of 50 MiB
[main                ] (input               )   DEBUG: using timeshift path: C:\Users\ADMINI~1\AppData\Local\Temp
[main                ] (input               )   DEBUG: `imem://' gives access `imem' demux `any' path `'
[main                ] (input source        )   DEBUG: creating demux: access='imem' demux='any' location='' file='(null)'
[main                ] (demux               )   DEBUG: looking for access_demux module matching "imem": zd candidates
[main                ] (demux               )   DEBUG: no access_demux modules matched
[main                ] (stream              )   DEBUG: creating access: imem://
[main                ] (stream              )   DEBUG: looking for access module matching "imem": zd candidates
[main                ] (stream              )   DEBUG: no access modules matched
[main                ] (input               )   ERROR: Your input can't be opened
[main                ] (input               )   ERROR: VLC is unable to open the MRL 'imem://'. Check the log for details.


well，I don't understand what does 'imem://' mean.Maybe it 's a protocol about memory？

**Comment by caprica** [comment] 2019-08-23 05:00
Is that log from running the vlcj test case or is it your own code?

Which version of vlcj are you using?

How did you install VLC? Was it using an official VLC installer?

imem is the protocol used by libVLC to play media using in memory callbacks.

**Comment by smokingrain** [comment] 2019-08-23 09:35
I downloaded VLC from official website,version : vlc-3.0.6-win64.My operations like this:
download vlc-3.0.6-win64.exe
install vlc-3.0.6-win64.exe
copy libvlc.dll,libvlccore.dll and plugins to your vlcj-player project;
uninstall vlc
run MinimalMediaCallbackTest.java;


so ,I should keep vlc in my computer ?

**Comment by caprica** [comment] 2019-08-23 09:47
Do not copy those DLLs. You should install VLC normally and then have vlcj find those DLLs in their usual place.

Do not uninstall VLC.

You can copy DLLs and uninstall VLC if you really know what you're doing but it is fraught with difficulties.

It is much easier if you just install and use VLC normally.
