### ISSUE TITLE
RTSP connection problem

### ISSUE THREAD

**Issue by ferrusqui** [caprica/vlcj#427] opened 2015-11-14 23:52 UTC
I'm trying to get the RTSP h264 stream from a foscam camera. 
I'm using the last VLC 64bit, my jdk is 64bit, my operative system is windows 7 64bit.

this is my code:

String mrl = new RtspMrl().host("192.168.0.106").port(88).path("/videoMain").value();
              
String[] options = {"--rtsp-user=admin", "--rtsp-pwd=admin"};

mediaPlayerComponent.getMediaPlayer().playMedia(mrl,options);

this is the log:
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[00000000004c14d0] core demux error: corrupt module: D:\vlc-2.2.0-win64\vlc-2.2.0\plugins\access\liblive555_plugin.dll
[000000000049de20] core input error: open of `rtsp://192.168.0.106:88/videoMain' failed
[000000000049de20] core input error: Your input can't be opened
[000000000049de20] core input error: VLC is unable to open the MRL 'rtsp://192.168.0.106:88/videoMain'. Check the log for details.

I tried to use VLC to get the stream, with the url rtsp://admin:admin@192.168.0.106:88/videoMain

and all works fine

any ideas?

**Comment by caprica** [comment] 2015-11-15 08:05
Please go through #362 and see if it explains your problem, it's a bit long...

**Comment by caprica** [comment] 2015-11-15 21:23
Actually, just re-reading this I spotted a "corrupt module" error, that's a native error coming from VLC itself.

I've seen a few reports of corrupt module on VLC 64-bit. I don't know the cause, but it's almost certainly nothing that can be "fixed" in vlcj.

**Comment by ferrusqui** [comment] 2015-11-15 23:36
Yes but if I try to use the same vlc directly it works fine. I can see the
video without errors. How is it possible?
More in general my question is also about the way to pass username and
password, is it correct the way I used?
Il 15/nov/2015 22:23, "Mark Lee" <notifications@github.com> ha scritto:

**Comment by caprica** [comment] 2015-11-16 08:32
According to the issue I linked for you, IIRC the username and password
works as part of the MRL.

The fact that you don't see a corrupt module error with VLC does not really
help here, because vlcj only loads libVLC and it is libVLC that loads
things like live555 as a plugin.

There is nothing that can be fixed in vlcj to solve native corrupt module
errors.

**Comment by ferrusqui** [comment] 2015-11-17 13:24
Thanks for the link, but it's no clear what's the correct mode to pass the
username and password. I can see some different examples but I didn't
understand the correct one.
Thanks
Il 16/nov/2015 09:32, "Mark Lee" <notifications@github.com> ha scritto:

> According to the issue I linked for you, IIRC the username and password
> works as part of the MRL.
>
> The fact that you don't see a corrupt module error with VLC does not really
> help here, because vlcj only loads libVLC and it is libVLC that loads
> things like live555 as a plugin.
>
> There is nothing that can be fixed in vlcj to solve native corrupt module
> errors.
>

**Closed** 2015-11-19 17:43 UTC
Labels: Support
